version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY
      - ANTHROPIC_API_KEY
      - JWT_SECRET
      - REDIS_URL
      - BASE_URL
      - ALLOWED_ORIGINS
      - DEV_MODE
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped